spring:
  datasource:
    url: jdbc:mysql:replication://127.0.0.1:3306,127.0.0.1:3307/test?createDatabaseIfNotExist=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&allowSourceDownConnections=true&allowReplicaDownConnections=true&readFromSourceWhenNoReplicas=true&retriesAllDown=1
#    url: jdbc:mysql:replication://address=(type=source)(host=127.0.0.1)(port=3306),address=(type=replica)(host=127.0.0.1)(port=3307)/test?createDatabaseIfNotExist=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&allowSourceDownConnections=true&allowReplicaDownConnections=true&readFromSourceWhenNoReplicas=true&retriesAllDown=1
    username: root
    password: 123456
